### ISSUE TITLE
java.lang.IllegalArgumentException: Last unit does not have enough valid bits

### ISSUE THREAD

**Issue by dshatz** [Kodein-Framework/Kodein-Memory#2]
We have a kotlin multiplatform application.

Kodein-DB: **0.6.1-beta**
KotlinxSerialization: **1.0.1**
Ktor: **1.5.2**

Models:
```kotlin
@Serializable
data class ProgramType(
    override val id: Int,
    val name: Translation,
    @SerialName("image_url") val imageUrl: String
): Metadata

@Serializable
data class Program(
    override val id: Int,
    val name: String = "",
    @SerialName("type_id") val typeId: Key<ProgramType>
): Metadata
``` 
Ktor is sending a request to our REST service, which produces JSON like this:
```
[
    {
        "id": 1,
        "name": "Google Chrome",
        "type_id": 4
    }
]

```
When `type_id` above is < 10, the following error is thrown when trying to deserialize that json into an instance of `Program`:

```
Caused by: java.lang.IllegalArgumentException: Last unit does not have enough valid bits
        at org.kodein.memory.text.Base64$Decoder.decode(Base64.kt:242)
        at org.kodein.memory.text.Base64$Decoder.decode$default(Base64.kt:200)
        at org.kodein.memory.text.Base64$Decoder.decode(Base64.kt:191)
        at org.kodein.memory.text.Base64$Decoder.decode(Base64.kt:185)
        at org.kodein.db.Key$KeySerializer.deserialize(Key.kt:22)
        at org.kodein.db.Key$KeySerializer.deserialize(Key.kt:19)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
```

Otherwise, works as expected.

**Comment by SalomonBrys** [comment]
In Kodein-DB, a key is a sequence of raw bytes, serialized in DB using base64.
In your example the JSON does not provide a key, but an Int.

Therefore your model is wrong, it should be:

```kotlin
@Serializable
data class Program(
    override val id: Int,
    val name: String = "",
    @SerialName("type_id") val typeId: Int // Int instead of Key<ProgramType>
): Metadata
```
